---
title: TTC delay data and Friday the 13th
author: Matthew Routley
date: '2017-06-21'
categories:
  - code
  - transit
slug: ttc-delay-data-and-friday-the-13th
---



<p>The TTC releasing their <a href="http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=fa6be8c5a612c510VgnVCM10000071d60f89RCRD">Subway Delay Data</a> was great news. I’m always happy to see more data released to the public. In this case, it also helps us investigate one of the great, enduring mysteries: Is Friday the 13th actually an unlucky day?</p>
<p>As always, we start by downloading and manipulating the data. I’ve added in two steps that aren’t strictly necessary. One is converting the Date, Time, and Day columns into a single Date column. The other is to drop most of the other columns of data, since we aren’t interested in them here.</p>
<pre class="r"><code>url &lt;- &quot;http://www1.toronto.ca/City%20Of%20Toronto/Information%20&amp;%20Technology/Open%20Data/Data%20Sets/Assets/Files/Subway%20&amp;%20SRT%20Logs%20(Jan01_14%20to%20April30_17).xlsx&quot;
filename &lt;- basename(url)
download.file(url, destfile = filename, mode = &quot;wb&quot;)
delays &lt;- readxl::read_excel(filename, sheet = 2) %&gt;% 
  dplyr::mutate(date = lubridate::ymd_hm(paste(`Date`, 
                                               `Time`, 
                                               sep = &quot; &quot;)),
                delay = `Min Delay`) %&gt;% 
  dplyr::select(date, delay)
delays</code></pre>
<pre><code>## # A tibble: 69,043 x 2
##                   date delay
##                 &lt;dttm&gt; &lt;dbl&gt;
##  1 2014-01-01 02:06:00     3
##  2 2014-01-01 02:40:00     0
##  3 2014-01-01 03:10:00     3
##  4 2014-01-01 03:20:00     5
##  5 2014-01-01 03:29:00     0
##  6 2014-01-01 07:31:00     0
##  7 2014-01-01 07:32:00     0
##  8 2014-01-01 07:34:00     0
##  9 2014-01-01 07:34:00     0
## 10 2014-01-01 07:53:00     0
## # ... with 69,033 more rows</code></pre>
<p>Now we have a <code>delays</code> dataframe with 69043 incidents starting from 2014-01-01 00:21:00 and ending at 2017-04-30 22:13:00.</p>
<p>We need to identify any days that are a Friday the 13th. We also might want to compare weekends, regular Fridays, other weekdays, and Friday the 13ths, so we add a <code>type</code> column that provides these values. Here we use the <code>case_when</code> function:</p>
<pre class="r"><code>delays &lt;- delays %&gt;% 
    dplyr::mutate(type = case_when( # Partition into Friday the 13ths, Fridays, weekends, and weekdays
      lubridate::wday(.$date) %in% c(1, 7) ~ &quot;weekend&quot;,
      lubridate::wday(.$date) %in% c(6) &amp; 
        lubridate::day(.$date) == 13 ~ &quot;Friday 13th&quot;,
      lubridate::wday(.$date) %in% c(6) ~ &quot;Friday&quot;,
      TRUE ~ &quot;weekday&quot; # Everything else is a weekday
  )) %&gt;% 
  dplyr::mutate(type = factor(type)) %&gt;% 
  dplyr::group_by(type)
delays</code></pre>
<pre><code>## # A tibble: 69,043 x 3
## # Groups:   type [4]
##                   date delay    type
##                 &lt;dttm&gt; &lt;dbl&gt;  &lt;fctr&gt;
##  1 2014-01-01 02:06:00     3 weekday
##  2 2014-01-01 02:40:00     0 weekday
##  3 2014-01-01 03:10:00     3 weekday
##  4 2014-01-01 03:20:00     5 weekday
##  5 2014-01-01 03:29:00     0 weekday
##  6 2014-01-01 07:31:00     0 weekday
##  7 2014-01-01 07:32:00     0 weekday
##  8 2014-01-01 07:34:00     0 weekday
##  9 2014-01-01 07:34:00     0 weekday
## 10 2014-01-01 07:53:00     0 weekday
## # ... with 69,033 more rows</code></pre>
<p>With the data organized, we can start with just a simple box plot of the minutes of delay by <code>type</code>.</p>
<pre class="r"><code>ggplot2::ggplot(delays, aes(type, delay)) +
  ggplot2::geom_boxplot() + 
  ggplot2::labs(x = &quot;Type&quot;, y = &quot;Minutes of delay&quot;)</code></pre>
<p><img src="/post/2017-06-19-ttc-delay-data-and-friday-the-13th_files/figure-html/box_plot-1.png" width="672" /></p>
<p>Not very compelling. Basically most delays are short (as in zero minutes long) with many outliers.</p>
<p>How about if we summed up the total minutes in delays for each of the types of days?</p>
<pre class="r"><code>delays %&gt;% 
  dplyr::summarise(total_delay = sum(delay))</code></pre>
<pre><code>## # A tibble: 4 x 2
##          type total_delay
##        &lt;fctr&gt;       &lt;dbl&gt;
## 1      Friday       18036
## 2 Friday 13th         619
## 3     weekday       78865
## 4     weekend       28194</code></pre>
<p>Clearly the total minutes of delays are much shorter for Friday the 13ths. But, there aren’t very many such days (only 6 in fact). So, this is a dubious analysis.</p>
<p>Let’s take a step back and calculate the average of the total delay across the entire day for each of the types of days. If Friday the 13ths really are unlucky, we would expect to see longer delays, at least relative to a regular Friday.</p>
<pre class="r"><code>daily_delays &lt;- delays %&gt;% # Total delays in a day
  dplyr::mutate(year = lubridate::year(date),
                day = lubridate::yday(date)) %&gt;% 
  dplyr::group_by(year, day, type) %&gt;% 
  dplyr::summarise(total_delay = sum(delay))

mean_daily_delays &lt;- daily_delays %&gt;% # Average delays in each type of day
  dplyr::group_by(type) %&gt;% 
  dplyr::summarise(avg_delay = mean(total_delay))
mean_daily_delays</code></pre>
<pre><code>## # A tibble: 4 x 2
##          type avg_delay
##        &lt;fctr&gt;     &lt;dbl&gt;
## 1      Friday 107.35714
## 2 Friday 13th 103.16667
## 3     weekday 113.63833
## 4     weekend  81.01724</code></pre>
<pre class="r"><code>ggplot2::ggplot(daily_delays, aes(type, total_delay)) +
  ggplot2::geom_boxplot() + 
  ggplot2::labs(x = &quot;Type&quot;, y = &quot;Total minutes of delay&quot;)</code></pre>
<p><img src="/post/2017-06-19-ttc-delay-data-and-friday-the-13th_files/figure-html/summary_box_plot-1.png" width="672" /></p>
<p>On average, Friday the 13ths have shorter total delays (103 minutes) than either regular Fridays (107 minutes) or other weekdays (114 minutes). Overall, weekend days have far shorter total delays (81 minutes).</p>
<p>If Friday the 13ths are unlucky, they certainly aren’t causing longer TTC delays.</p>
<p>For the statisticians among you that still aren’t convinced, we’ll run a basic linear model to compare Friday the 13ths with regular Fridays. This should control for many unmeasured variables.</p>
<pre class="r"><code>model &lt;- lm(total_delay ~ type, data = daily_delays, 
            subset = type %in% c(&quot;Friday&quot;, &quot;Friday 13th&quot;))
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = total_delay ~ type, data = daily_delays, subset = type %in% 
##     c(&quot;Friday&quot;, &quot;Friday 13th&quot;))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -103.357  -30.357   -6.857   18.643  303.643 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      107.357      3.858  27.829   &lt;2e-16 ***
## typeFriday 13th   -4.190     20.775  -0.202     0.84    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 50 on 172 degrees of freedom
## Multiple R-squared:  0.0002365,  Adjusted R-squared:  -0.005576 
## F-statistic: 0.04069 on 1 and 172 DF,  p-value: 0.8404</code></pre>
<p>Definitely no statistical support for the idea that Friday the 13ths cause longer TTC delays.</p>
<p>How about time series tests, like <a href="https://blog.statsbot.co/time-series-anomaly-detection-algorithms-1cef5519aef2">anomaly detections</a>? Seems like we’d just be getting carried away. Part of the art of statistics is knowing when to quit.</p>
<p>In conclusion, then, after likely far too much analysis, we find no evidence that Friday the 13ths cause an increase in the length of TTC delays. This certainly suggests that Friday the 13ths are not unlucky in any meaningful way, at least for TTC riders.</p>
<p>Glad we could put this superstition to rest!</p>
<!-- I'd argue that what really matters is the length of delays, as we've analyzed above. But, some might say that it is the number of delays that matters. So, let's take a look: -->
<!-- ```{r frequencies} -->
<!-- delays %>% -->
<!--   dplyr::mutate(year = lubridate::year(date), -->
<!--                 day = lubridate::yday(date)) %>%  -->
<!--   dplyr::group_by(year, day, type) %>%  -->
<!--   dplyr::summarise(number_delays = n()) %>%  -->
<!--   dplyr::group_by(type) %>%  -->
<!--   dplyr::summarise(avg_number_delays = mean(number_delays)) -->
<!-- ``` -->
<!-- Nope. All weekdays have about the same number of delays, while weekends have about a third less delays. -->
